suppressPackageStartupMessages({library(ggplot2);library(dplyr);library(tidyr);library(readr)})
po<-read_csv('final_outcomes/W16_factorial_pooled.csv',show_col_types=FALSE)
wi<-read_csv('final_outcomes/W16_factorial_within_model.csv',show_col_types=FALSE)
regs<-c('Aggregated R10 regions','R10AFRICA','R10CHINA+','R10EUROPE','R10INDIA+','R10LATIN_AM','R10MIDDLE_EAST','R10NORTH_AM','R10REF_ECON','R10REST_ASIA','R10PAC_OECD')
reglabs<-c('WORLD','Africa','China+','Europe','India+','Latin America','Middle East','North America','Reforming economies','Rest of Asia','Pacific OECD*')
fams<-c('POOLED','AIM','COFFEE','GCAM','IMAGE','MESSAGEix','POLES','REMIND','TIAM','WITCH')
ambs<-c('All ambitions','1.5C','2C'); dbs<-c('Full','SCI-vetted')
base<-expand_grid(database=dbs,ambition_view=ambs,Region=regs,outcome_label=unique(po$outcome_label),fam=fams)
pool_cells<-po%>%transmute(database,ambition_view,Region,outcome_label,fam='POOLED',favours,score=sign(effect),n_cdr,n_re,robust=TRUE)
within_cells<-wi%>%transmute(database,ambition_view,Region,outcome_label,fam,favours,score=sign(delta),n_cdr,n_re,robust)
cells<-base%>%left_join(bind_rows(pool_cells,within_cells),by=c('database','ambition_view','Region','outcome_label','fam'))%>%
 mutate(database=factor(database,levels=dbs),ambition_view=factor(ambition_view,levels=ambs),fam=factor(fam,levels=fams),Region=factor(Region,levels=rev(regs),labels=rev(reglabs)),lab=case_when(score>0&robust~'RE',score>0&!robust~'RE*',score<0&robust~'CDR',score<0&!robust~'CDR*',score==0&robust~'=',score==0&!robust~'=*',TRUE~''))
cols<-c('High-RE'='#16859C','High-CDR'='#C56D42','Tie'='#C5CDD4')
theme_compass<-theme_minimal(base_family='Arial',base_size=12)+theme(panel.grid=element_blank(),strip.text=element_text(face='bold',color='#142A3D',size=11),axis.title=element_blank(),axis.text=element_text(color='#293746'),plot.title=element_text(face='bold',size=19,color='#142A3D'),plot.subtitle=element_text(size=11,color='#5C6F82'),plot.caption=element_text(size=9,color='#5C6F82'),legend.position='bottom',plot.margin=margin(12,20,10,18))
world<-cells%>%filter(Region=='WORLD')
p<-ggplot(world,aes(fam,outcome_label,fill=favours))+geom_tile(color='white',linewidth=1)+geom_text(aes(label=lab),fontface='bold',size=3.4,color='#142A3D')+facet_grid(database~ambition_view)+scale_fill_manual(values=cols,na.value='#EEF1F3',drop=FALSE)+scale_x_discrete(labels=c('POOLED'='POOLED','MESSAGEix'='MESSAGE-ix'))+labs(title='World: pooled direction beside every within-model comparison',subtitle='RE/CDR = at least 3 scenarios per arm; RE*/CDR* = descriptive comparison with only 1–2 scenarios in at least one arm; blank = one arm absent.',caption='Portfolio labels are defined within ambition first. All ambitions pools those classified scenarios; it does not redefine the tercile thresholds.',fill='Direction')+theme_compass+theme(axis.text.x=element_text(angle=35,hjust=1),axis.text.y=element_text(size=10))
ggsave('final_outcomes/W16_world_factorial_matrix.png',p,width=16,height=9,dpi=240,bg='white')
for(out in unique(cells$outcome_label)){
 z<-cells%>%filter(outcome_label==out)
 q<-ggplot(z,aes(fam,Region,fill=favours))+geom_tile(color='white',linewidth=.8)+geom_text(aes(label=lab),fontface='bold',size=2.5,color='#142A3D')+facet_grid(database~ambition_view)+scale_fill_manual(values=cols,na.value='#EEF1F3',drop=FALSE)+scale_x_discrete(labels=c('POOLED'='POOL','MESSAGEix'='MESSAGE'))+labs(title=paste0(out,': pooled and within-model directions at World and R10 level'),subtitle="RE/CDR = at least 3 scenarios per arm; starred cells use only 1–2 scenarios in at least one arm; blank = one arm absent.",caption='Pacific OECD is retained diagnostically and marked with an asterisk. Thin-sample cells are descriptive only; no causal interpretation.',fill='Direction')+theme_compass+theme(axis.text.x=element_text(angle=35,hjust=1,size=8.5),axis.text.y=element_text(size=8.5))
 fn<-gsub('[^A-Za-z0-9]+','_',tolower(out));ggsave(file.path('final_outcomes',paste0('W16_regional_',fn,'.png')),q,width=16,height=9,dpi=240,bg='white')
}
