import { Presentation, PresentationFile } from '@oai/artifact-tool';

const OUT='C:/Users/camwe/Documents/Codex/2026-08-22/i-a/outputs/COMPASS_Paper1_final_submission_deck_styled_8_22.pptx';
const W=1280,H=720;
const C={navy:'10293D',ink:'25323D',muted:'667684',line:'D9E0E2',paper:'FCFCFA',orange:'C4872B',cyan:'72AEC1',blue:'39738B',green:'429568',red:'BE5654',paleBlue:'EAF2F5',paleOrange:'FAF1E5',paleGreen:'EAF5EE',paleRed:'F9ECEB',gray:'F2F4F3'};
const p=Presentation.create({slideSize:{width:W,height:H}});

function box(s,x,y,w,h,fill='none',line='none',geom='rect') { return s.shapes.add({geometry:geom,position:{left:x,top:y,width:w,height:h},fill,line:{style:'solid',fill:line,width:line==='none'?0:1}}); }
function tx(s,x,y,w,h,text,size=18,color=C.ink,bold=false,font='Aptos',align='left') { const q=box(s,x,y,w,h); q.text=text; q.text.style={fontSize:size,color,bold,fontFace:font,align,margin:0,breakLine:false}; return q; }
function rich(s,x,y,w,h,runs,size=16){ const q=box(s,x,y,w,h); q.text=runs.map(r=>({text:r.text,style:{fontSize:r.size||size,color:r.color||C.ink,bold:!!r.bold,fontFace:r.font||'Aptos',breakLine:false}})); return q; }
function line(s,x,y,w,color=C.line){s.shapes.add({geometry:'line',position:{left:x,top:y,width:w,height:0},line:{style:'solid',fill:color,width:1}});}
function body(s,section,title,num,tag=''){s.background.fill=C.paper; tx(s,72,28,520,17,section.toUpperCase(),10,C.orange,true,'Aptos');tx(s,990,28,218,17,tag.toUpperCase(),10,C.cyan,true,'Aptos','right');tx(s,72,58,1136,62,title,30,C.ink,true,'Georgia');line(s,72,143,1136);tx(s,72,682,740,14,'COMPASS Scenario Database · Paper 1 · 2020–2100',9,C.muted,false,'Aptos');tx(s,1172,682,36,14,String(num).padStart(2,'0'),9,C.muted,true,'Aptos','right');}
function divider(title,sub,num){const s=p.slides.add();s.background.fill=C.navy;tx(s,76,116,300,18,`PART ${num}`,11,C.cyan,true,'Aptos');tx(s,76,230,1040,80,title,37,'FFFFFF',true,'Georgia');tx(s,76,330,900,36,sub,17,'C9D7DF',false,'Aptos');return s;}
function bullet(s,x,y,w,title,copy,color=C.blue){tx(s,x,y,w,19,title.toUpperCase(),11,color,true,'Aptos');tx(s,x,y+28,w,82,copy,15,C.ink,false,'Aptos');}
function callout(s,x,y,w,h,label,main,copy,fill=C.paleBlue,accent=C.blue){box(s,x,y,w,h,fill,'none');box(s,x,y,5,h,accent,'none');tx(s,x+18,y+17,w-36,16,label.toUpperCase(),10,accent,true,'Aptos');tx(s,x+18,y+42,w-36,66,main,25,C.ink,true,'Georgia');tx(s,x+18,y+122,w-36,h-137,copy,13,C.muted,false,'Aptos');}
function miniTable(s,x,y,w,headers,rows,widths){const rowH=27; box(s,x,y,w,rowH,'EDF2F3','none');let cx=x;headers.forEach((h,i)=>{tx(s,cx+7,y+6,widths[i]-12,15,h,10,C.blue,true,'Aptos');cx+=widths[i];});rows.forEach((row,ri)=>{let yy=y+rowH*(ri+1);if(ri%2===1)box(s,x,yy,w,rowH,'F7F8F7','none');let xx=x;row.forEach((v,i)=>{const favorable=String(v).startsWith('−') && (row.join(' ').includes('gap')||row.join(' ').includes('headcount')||row.join(' ').includes('deaths')||row.join(' ').includes('1.5°C'));tx(s,xx+7,yy+6,widths[i]-12,15,v,11,favorable?C.green:C.ink, i===0,'Aptos');xx+=widths[i];});});}
function bars(s,x,y,w,items,max=700){items.forEach((it,i)=>{const yy=y+i*47;tx(s,x,yy,w*.36,18,it.label,12,C.ink,true,'Aptos');const bw=Math.abs(it.value)/max*w*.58;box(s,x+w*.39,yy+4,bw,14,it.color,'none');tx(s,x+w*.39+bw+8,yy,w*.20,18,it.text,12,it.color,true,'Aptos');});}
function addNotes(s,n){try{s.notes.setText(`[Sources]\n${n}`);s.notes.setVisible(true);}catch{}}

// 1 — opening
{const s=p.slides.add();s.background.fill=C.navy;tx(s,76,88,510,18,'COMPASS SCENARIO DATABASE · DISSERTATION PAPER 1',10,C.cyan,true,'Aptos');tx(s,76,180,1040,108,'High renewables or engineered carbon management?',42,'FFFFFF',true,'Georgia');tx(s,76,311,950,48,'Century-long wellbeing implications across global IAM pathways',22,'D8E2E7',false,'Aptos');line(s,76,455,230,C.cyan);tx(s,76,480,850,48,'World results first. R10 regions explain the pattern. Transparent diagnostics define the limits.',16,'C4D5DD',false,'Aptos');tx(s,76,646,420,18,'Final analysis · primary classification excludes land-based CDR',11,'9CBAC6',false,'Aptos');}

// 2
{const s=p.slides.add();body(s,'The paper in one view','Three conclusions, with different evidentiary strength',2,'EXECUTIVE SUMMARY');callout(s,72,186,350,300,'1 · jobs','High-RE is higher','Across the full ensemble, High-RE has substantially more modeled renewable electricity job-years at both ambition levels.',C.paleGreen,C.green);callout(s,465,186,350,300,'2 · energy deprivation','High-RE is generally lower','The full database shows lower modeled energy gap and deprivation headcount. SCI 2°C results are heterogeneous.',C.paleBlue,C.blue);callout(s,858,186,350,300,'3 · mortality','No universal winner','The reporting-complete PM2.5 diagnostic is useful, but coverage and composition prevent a headline portfolio ranking.',C.paleRed,C.red);addNotes(s,'All findings are based on the local final COMPASS output tables.');}

// 3
{const s=p.slides.add();body(s,'Research question','The comparison is deliberately two-part',3,'DESIGN');bullet(s,72,190,500,'Wellbeing question','Across World and R10 regions, what differs between renewable-intensive and engineered-carbon-management-intensive pathways at the same climate ambition?',C.orange);bullet(s,72,340,500,'Diagnostic question','Are pooled contrasts carried by a particular IAM composition, regional pattern, or reporting subset?',C.orange);box(s,663,188,520,272,C.paleBlue,'none');tx(s,700,220,445,23,'Every pathway is compared within its ambition cell',23,C.ink,true,'Georgia');tx(s,700,275,430,130,'1.5°C and 2°C are never pooled. Full-database results describe the ensemble; SCI-vetted results are reported separately. Within-model contrasts test whether composition is driving the pooled pattern.',16,C.ink,false,'Aptos');}

// 4
{const s=p.slides.add();body(s,'Classification','The primary contrast is RE versus engineered CMT—not “all removals”',4,'PORTFOLIO IDENTITY');miniTable(s,72,188,1136,['Arm','Focal deployment','Exclusion rule','Why'],[['High-RE','Top tercile: renewable capacity','Engineered CMT not top tercile','Identifies RE-led portfolios'],['High engineered-CMT','Top tercile: novel CDR + fossil/industrial CCS','Renewables not top tercile','Identifies engineered-management portfolios'],['Land CDR','Excluded from primary axis','Retained for “all-removals” sensitivity','Keeps the energy-system motivation distinct']], [170,300,280,386]);tx(s,72,391,1136,28,'Classification uses cumulative 2020–2100 deployment, so labels describe long-run portfolios rather than a single benchmark year.',16,C.ink,true,'Georgia');tx(s,72,445,1136,45,'Sensitivity analyses retain the strict polar rule and the total-CDR (all-removals) question; neither substitutes for the primary engineered-CMT contrast.',15,C.muted,false,'Aptos');}

// 5
{const s=p.slides.add();body(s,'Sample coverage','The final full-database contrast is larger than the earlier total-CDR sample',5,'TRANSPARENCY');miniTable(s,72,188,765,['Sample / ambition','High-RE','High engineered-CMT','Comparison count'],[['Full · 1.5°C','64','64','128'],['Full · 2°C','239','239','478'],['SCI · 1.5°C','7','7','14'],['SCI · 2°C','63','63','126']], [250,150,220,145]);box(s,875,188,333,231,C.paleOrange,'none');tx(s,904,218,275,20,'SCI 1.5°C is intentionally small',18,C.orange,true,'Georgia');tx(s,904,260,272,112,'24 candidates → 22 classifiable → 7 pathways per arm. Two candidates lack the classification metrics; eight fall outside the paired arms.',14,C.ink,false,'Aptos');tx(s,72,475,1136,48,'New engineered-CMT primary classification: 606 selected full-database pathways and 140 SCI-vetted pathways. Earlier deck: 579 and 106 under total CDR.',15,C.ink,true,'Georgia');}

divider('Methodology','Scenario outputs are translated into bounded wellbeing-relevant indicators.',1);

// 7
{const s=p.slides.add();body(s,'Methodology · electricity employment','Capacity deployment becomes gross/direct electricity job-years',7,'OUTCOME 1');miniTable(s,72,190,1136,['Stage','Input / operation','Meaning'],[['IAM output','R10 technology-specific capacity additions and operating capacity','The deployment pathway'],['Post-processing','Published manufacturing, construction, installation, and O&M employment factors','Job-years by technology'],['Outcome','Renewable electricity job-years per 1,000 people','Not net economy-wide employment or job quality']], [220,500,416]);tx(s,72,405,1136,28,'Mechanism: wind and solar generally require more distributed manufacturing, construction, installation, and operations activity per unit of capacity.',16,C.ink,true,'Georgia');bullet(s,72,473,510,'Mechanical WHY','High-RE portfolios build more RE capacity; CMT investment shifts more system effort to removal, capture, storage, and fuel supply.',C.blue);bullet(s,655,473,510,'Policy WHY','Domestic content, workforce programs, grid build-out, and trade determine whether modeled activity becomes local employment.',C.orange);}

// 8
{const s=p.slides.add();body(s,'Methodology · energy deprivation','Final energy availability becomes two modeled decent-living indicators',8,'OUTCOMES 2–3');miniTable(s,72,186,1136,['Indicator','IAM input','Post-processing / interpretation'],[['Energy gap (GJ/cap)','Regional final energy and population','Energy needed to lift people below a regional decent-living threshold'],['Headcount (%)','Regional final energy per person','Threshold + lognormal within-region distribution + inequality parameter']], [235,355,546]);tx(s,72,390,1136,24,'These are distributional final-energy-deprivation proxies—not observed household access, consumption surveys, or income poverty.',16,C.red,true,'Georgia');bullet(s,72,463,500,'Mechanical WHY','RE-intensive pathways often co-occur with electrification and higher final-energy availability relative to the threshold.',C.blue);bullet(s,654,463,500,'Policy WHY','Grid access, affordability, reliability, appliances, and tariff design decide whether supply reaches people.',C.orange);}

// 9
{const s=p.slides.add();body(s,'Methodology · mortality','PM2.5 mortality is a reporting-complete, coverage-qualified diagnostic',9,'OUTCOME 4');miniTable(s,72,186,1136,['Stage','Decision','Reason'],[['Emission inputs','Direct R10 SO₂, NOₓ, BC, OM, NH₃ only','No World-to-R10 allocation; no external NH₃ sidecar'],['Air-quality response','TM5-FASST → PM2.5 exposure → FUSION mortality response','Consistent, fast scenario post-processing'],['Coverage rule','Only complete precursor records enter final comparison','Reject rather than fill structurally missing pathways']], [230,458,448]);box(s,72,407,1136,93,C.paleRed,'none');tx(s,96,430,1085,48,'422 valid PM2.5 outputs from 643 classified targets; 150 incomplete records rejected. Short interior interpolation was permitted, but no values were interpolated.',15,C.ink,true,'Georgia');tx(s,72,535,1136,43,'Interpretation: PM2.5-attributable mortality only, not total air-pollution mortality—and not a universal High-RE vs High-CMT rank.',15,C.red,true,'Aptos');}

// 10
{const s=p.slides.add();body(s,'Methods logic','The path from scenario portfolio to wellbeing outcome is explicit',10,'MECHANISM');tx(s,72,196,1136,22,'Technology portfolio',13,C.orange,true,'Aptos');box(s,72,230,220,75,C.paleOrange,'none');tx(s,90,250,184,33,'IAM pathway',25,C.ink,true,'Georgia');tx(s,327,196,250,22,'Physical output',13,C.orange,true,'Aptos');box(s,327,230,220,75,C.paleBlue,'none');tx(s,348,250,180,33,'R10 variables',25,C.ink,true,'Georgia');tx(s,582,253,60,26,'→',24,C.muted,true,'Georgia','center');tx(s,677,196,270,22,'Post-processing',13,C.orange,true,'Aptos');box(s,677,230,220,75,C.paleGreen,'none');tx(s,698,250,180,33,'Outcome model',25,C.ink,true,'Georgia');tx(s,933,253,60,26,'→',24,C.muted,true,'Georgia','center');tx(s,1018,196,180,22,'Interpretation',13,C.orange,true,'Aptos');box(s,1018,230,190,75,C.gray,'none');tx(s,1040,250,148,33,'Wellbeing',25,C.ink,true,'Georgia');line(s,72,365,1136);bullet(s,72,405,330,'Jobs','Capacity × employment factors',C.green);bullet(s,452,405,330,'Energy deprivation','Final energy × threshold + distribution',C.green);bullet(s,832,405,330,'Mortality','Precursors × TM5-FASST × FUSION',C.green);}

divider('Results','World results provide the takeaway. R10 results show why it appears.',2);

// 12
{const s=p.slides.add();body(s,'Results · World','Full database: High-RE is higher on jobs and lower on modeled energy deprivation',12,'WORLD · PRIMARY');miniTable(s,72,185,1136,['Outcome (High-RE − High engineered-CMT)','1.5°C','2°C','Direction'],[['RE job-years per 1,000 people','+396  (687 vs 291)','+288  (461 vs 173)','High-RE higher'],['Energy gap, GJ/cap','−5.7  (13.0 vs 18.7)','−4.5  (11.1 vs 15.5)','High-RE lower'],['Deprivation headcount, pp','−2.25  (4.61 vs 6.86)','−1.77  (4.02 vs 5.80)','High-RE lower']], [440,230,230,236]);tx(s,72,370,1136,30,'The two ambitions differ in scale—not in the full-database direction for the three non-mortality outcomes.',17,C.ink,true,'Georgia');bars(s,72,450,520,[{label:'1.5°C jobs',value:396,text:'+396',color:C.green},{label:'2°C jobs',value:288,text:'+288',color:C.green}],450);bars(s,682,450,520,[{label:'1.5°C energy gap',value:5.7,text:'−5.7 GJ/cap',color:C.green},{label:'2°C energy gap',value:4.5,text:'−4.5 GJ/cap',color:C.green}],6);addNotes(s,'Source: century_outcome_medians_no_land_engineered_cmt.csv, approach A, Aggregated R10 regions.');}

// 13
{const s=p.slides.add();body(s,'Results · World','SCI-vetted evidence confirms the jobs contrast; 2°C deprivation is not uniform',13,'WORLD · SCI');miniTable(s,72,185,1136,['Outcome (High-RE − High engineered-CMT)','SCI 1.5°C','SCI 2°C','Reading'],[['RE job-years per 1,000 people','+262  (526 vs 264)','+111  (293 vs 182)','Jobs remain higher'],['Energy gap, GJ/cap','−2.4  (18.4 vs 20.8)','+1.5  (20.5 vs 19.0)','2°C reverses'],['Deprivation headcount, pp','−0.99  (6.86 vs 7.85)','+0.73  (7.60 vs 6.87)','2°C reverses']], [440,230,230,236]);box(s,72,385,1136,102,C.paleOrange,'none');tx(s,96,409,1080,46,'The SCI sample is a different evidence set—not a “cleaner” version of the full ensemble. Report the divergence rather than averaging it away.',17,C.ink,true,'Georgia');tx(s,72,530,1136,35,'SCI sample sizes: 7 vs 7 at 1.5°C; 63 vs 63 at 2°C.',14,C.muted,false,'Aptos');}

// 14
{const s=p.slides.add();body(s,'Results · mortality','The reporting-complete PM2.5 diagnostic has no stable pooled portfolio winner',14,'WORLD · DIAGNOSTIC');miniTable(s,72,185,1136,['Sample','1.5°C: RE − CMT, million deaths','2°C: RE − CMT, million deaths','Interpretation'],[['Full database','−8.69','+3.03','Pooled direction changes'],['SCI-vetted','−50.42','+22.45','Pooled direction changes']], [200,310,310,316]);bullet(s,72,350,500,'What is stable','At 2°C, matched within-model full-database comparisons all point toward lower High-RE mortality, but only three models qualify.',C.green);bullet(s,655,350,500,'What is not stable','Coverage differs by arm and model family; pooled medians change with sample composition. The paper should not rank portfolios on mortality.',C.red);tx(s,72,530,1136,34,'Coverage is reported with every mortality result: e.g., full 1.5°C 42/64 CMT vs 37/64 RE; full 2°C 138/239 vs 168/239.',14,C.muted,false,'Aptos');addNotes(s,'Source: mortality_reporting_complete_medians_2020_2100.csv and mortality_reporting_complete_coverage_2020_2100.csv.');}

// 15
{const s=p.slides.add();body(s,'Results · interpretation','The mortality caveat is a result about evidence quality—not a weakness to hide',15,'DIAGNOSTIC');callout(s,72,190,350,275,'Coverage','Missing precursor reporting is structural','Scenarios that lack a required pollutant cannot support a comparable PM2.5 mortality estimate.',C.paleRed,C.red);callout(s,465,190,350,275,'Composition','Pooled arms contain different IAM mixtures','A pooled median can move even when the qualifying within-model comparison has a different direction.',C.paleOrange,C.orange);callout(s,858,190,350,275,'Bounded claim','Mortality is a QA check','It tests whether air-quality implications are plausible under complete reporting; it does not establish a global ranking.',C.paleBlue,C.blue);tx(s,72,527,1136,38,'This is why the paper leads with jobs and energy deprivation, then shows mortality transparently as a qualified diagnostic.',17,C.ink,true,'Georgia');}

divider('Regional diagnosis','World results are aggregation outcomes: regions differ in stakes, scale, and mechanisms.',3);

// 17
{const s=p.slides.add();body(s,'Results · R10 jobs','High-RE produces more modeled RE job-years in almost every region',17,'R10 · PRIMARY');miniTable(s,72,178,850,['Region','1.5°C RE − CMT','2°C RE − CMT','Signal'],[['Africa','+832','+538','largest positive'],['India+','+733','+455','large positive'],['Rest of Asia','+666','+442','large positive'],['Middle East','+557','+411','large positive'],['Latin America','+221','+194','positive'],['China+','+124','+91','positive'],['North America','+154','+103','positive'],['Europe','+63','+58','positive']], [245,180,180,245]);box(s,956,178,252,294,C.paleOrange,'none');tx(s,980,204,205,20,'Exceptions are small',18,C.orange,true,'Georgia');tx(s,980,244,202,150,'Pacific OECD is near zero or modestly positive; no R10 region reverses the strong global jobs result in both ambitions.',14,C.ink,false,'Aptos');tx(s,72,525,1136,33,'Values are High-RE − High engineered-CMT renewable job-years per 1,000 people; they quantify modeled sectoral activity, not labour-market welfare.',14,C.muted,false,'Aptos');}

// 18
{const s=p.slides.add();body(s,'Results · R10 energy deprivation','The World deprivation result is driven by high-stakes regions—but it is not universal',18,'R10 · PRIMARY');miniTable(s,72,178,1136,['Region','Energy gap difference: 1.5°C / 2°C','Headcount difference: 1.5°C / 2°C','Reading'],[['Africa','−22.1 / −24.8 GJ/cap','−10.0 / −9.5 pp','largest improvement'],['Latin America','−23.1 / −11.4 GJ/cap','−7.6 / −3.4 pp','large improvement'],['India+','−0.6 / −0.7 GJ/cap','−0.5 / −0.7 pp','modest improvement'],['Rest of Asia','−2.3 / +3.0 GJ/cap','−0.9 / +1.0 pp','ambition-dependent'],['Middle East / North America','positive gaps','positive headcounts','reversal']], [220,330,330,256]);tx(s,72,386,1136,40,'Negative values favor High-RE. The regional pattern makes the World average interpretable: high baseline shortfalls magnify changes in final energy availability.',16,C.ink,true,'Georgia');}

// 19
{const s=p.slides.add();body(s,'Results · regional mortality','Read PM2.5 mortality only where the precursor-reporting comparison is complete',19,'R10 · DIAGNOSTIC');bullet(s,72,195,500,'Where World totals come from','Large populations and high baseline pollution make South and East Asian regions central to absolute PM2.5 mortality totals.',C.blue);bullet(s,72,355,500,'Why regional direction differs','Coal, industry, transport, biomass, agricultural NH₃, and the pace of end-use electrification vary across R10 regions.',C.orange);box(s,655,195,553,278,C.paleRed,'none');tx(s,687,226,480,26,'Do not convert incomplete reporting into a regional causal story',22,C.red,true,'Georgia');tx(s,687,279,460,128,'A regional contrast is reported only when both pathway arms contain complete direct R10 precursor emissions and comparable models. This prevents a “clean-looking” map from hiding missing NH₃ or other precursors.',16,C.ink,false,'Aptos');}

// 20
{const s=p.slides.add();body(s,'Regional diagnosis','Which regions mechanically drive the World story?',20,'SYNTHESIS');callout(s,72,190,350,280,'Scale','China+, India+, Rest of Asia','Large deployment volumes and population mean these regions can dominate world job-years and PM2.5 totals.',C.paleBlue,C.blue);callout(s,465,190,350,280,'Stakes','Africa, India+, Latin America','High starting energy shortfalls mean a change in final energy availability moves the deprivation indicators most.',C.paleGreen,C.green);callout(s,858,190,350,280,'Divergence','Middle East, North America, Pacific OECD','Fossil-asset structure, trade, resource quality, and modelled energy demand can produce different deprivation patterns.',C.paleOrange,C.orange);tx(s,72,528,1136,34,'World is not a vote count across R10 regions: it is a population-, energy-, and deployment-weighted aggregation.',16,C.ink,true,'Georgia');}

divider('Why the patterns arise','The results describe scenario portfolios; the mechanism is technological, distributional, and policy-mediated.',4);

// 22
{const s=p.slides.add();body(s,'Mechanisms','Why the job-years result is mechanically plausible',22,'WHY · JOBS');miniTable(s,72,190,1136,['Portfolio feature','System consequence','Wellbeing-relevant implication'],[['High-RE','More wind/solar additions and operating capacity','More modeled manufacturing, construction, installation, and O&M job-years'],['High engineered-CMT','More capture/removal/storage and remaining fuel-system activity','Less RE-build activity per person—without implying fewer total economy jobs'],['Regional context','Supply chains, labour intensity, import dependence','Modeled job activity need not equal domestic job quality or inclusion']], [270,420,446]);tx(s,72,404,1136,48,'Real-world policy bridge: renewable targets alone are not a workforce strategy. Grid planning, training, local-content rules, labour standards, and just-transition policy determine who benefits.',16,C.ink,true,'Georgia');}

// 23
{const s=p.slides.add();body(s,'Mechanisms','Why deprivation can improve—and can reverse—by region',23,'WHY · ENERGY');bullet(s,72,195,500,'Mechanical pathway','Technology portfolios co-vary with electrification, efficiency, fuel switching, and final energy availability. The DLE model translates those changes relative to a regional threshold.',C.blue);bullet(s,72,374,500,'Why Africa and Latin America matter','A given change in available final energy can reduce a large shortfall or affect a large population below the threshold.',C.green);bullet(s,655,195,500,'Why reversals are credible','CMT-intensive scenarios can still deploy substantial renewables; demand, end-use allocation, model structure, and trade can outweigh the portfolio label in a region.',C.orange);bullet(s,655,374,500,'Policy bridge','Affordable connections, reliability, productive-use demand, appliance efficiency, and tariff design are the missing links between energy supply and household wellbeing.',C.orange);}

// 24
{const s=p.slides.add();body(s,'Mechanisms · mortality','Why High-RE and High engineered-CMT can look similar on PM2.5',24,'WHY · AIR QUALITY');tx(s,72,190,1136,28,'Both pathways meet the same temperature target; “High engineered-CMT” does not mean “high fossil pollution.”',20,C.ink,true,'Georgia');miniTable(s,72,251,1136,['Reason','How it affects the comparison'],[['Shared mitigation','1.5°C and 2°C CMT scenarios still reduce fossil combustion and deploy renewables, so both can receive large pollution-health benefits.'],['Non-power sources','Industry, transport, biomass, agriculture, and NH₃ drive PM2.5 too; a power-sector portfolio label cannot isolate all precursors.'],['Evidence constraint','Complete emissions reporting differs across model families and pathway arms, shifting pooled medians.']], [250,886]);tx(s,72,505,1136,37,'Policy implication: achieving the climate target is necessary for cleaner air, but the co-benefit depends on which emitting sectors are transformed and how completely emissions are reported.',15,C.ink,true,'Georgia');}

// 25
{const s=p.slides.add();body(s,'Diagnostic evidence','Model composition is a core result, not an appendix footnote',25,'ROBUSTNESS');box(s,72,188,510,290,C.paleBlue,'none');tx(s,100,218,450,22,'Pooled ensemble',21,C.blue,true,'Georgia');tx(s,100,261,438,150,'Describes the set of scenarios observed in the database. It can mix different IAM families across the two portfolio arms, especially after requiring outcome coverage.',16,C.ink,false,'Aptos');box(s,698,188,510,290,C.paleGreen,'none');tx(s,726,218,450,22,'Within-model comparison',21,C.green,true,'Georgia');tx(s,726,261,438,150,'Keeps an IAM only when it supplies both pathway arms in the same ambition-region cell. It is the better test of whether the pooled contrast is model-composition dependent.',16,C.ink,false,'Aptos');tx(s,72,530,1136,38,'Use association language for pooled results. Treat agreement between pooled and within-model evidence as stronger support; show disagreement as diagnosis.',16,C.ink,true,'Georgia');}

// 26
{const s=p.slides.add();body(s,'Robustness','The primary result is distinguished from related sensitivity questions',26,'ROBUSTNESS');miniTable(s,72,190,1136,['Specification','What it tests','Role in paper'],[['Primary: engineered-CMT, broad paired top-tercile rule','Energy-system contrast: High-RE vs novel CDR + fossil/industrial CCS','Main findings'],['Strict polar portfolios','Whether technology extremes sharpen or alter the contrast','Sensitivity'],['Total CDR / all removals','Whether land removals change the interpretation','Supplement: different substantive question'],['Mortality reporting-complete screen','Whether PM2.5 conclusions survive complete direct R10 inputs','QA diagnostic']], [390,495,251]);tx(s,72,413,1136,42,'Robustness does not mean forcing every outcome to agree. It means specifying which comparison each statistic can credibly answer.',16,C.ink,true,'Georgia');}

// 27
{const s=p.slides.add();body(s,'Paper contribution','A precise and dissertation-ready claim set',27,'CONTRIBUTION');tx(s,72,190,1136,26,'The paper can credibly claim that:',20,C.ink,true,'Georgia');bullet(s,92,247,1040,'1','Within the full global IAM ensemble, High-RE pathways are associated with substantially more modeled RE job-years and generally lower modeled energy deprivation than High engineered-CMT pathways.',C.green);bullet(s,92,361,1040,'2','R10 heterogeneity explains the World patterns: high-stakes deprivation regions and high-scale deployment regions matter more than a region-count average.',C.green);bullet(s,92,475,1040,'3','PM2.5 mortality is informative only after reporting-complete screening and remains non-rankable across all samples and ambitions—an evidence-quality result with substantive value.',C.red);}

// 28
{const s=p.slides.add();s.background.fill=C.navy;tx(s,76,120,320,18,'BOTTOM LINE',11,C.cyan,true,'Aptos');tx(s,76,224,1080,90,'High-RE pathways carry the clearer wellbeing advantage where the evidence is strongest.',37,'FFFFFF',true,'Georgia');tx(s,76,350,1020,74,'They are associated with more renewable-electricity job-years and—across the full ensemble—less modeled energy deprivation. Regional diagnosis makes that global result interpretable; transparent mortality coverage keeps the claim honest.',19,'D4E0E6',false,'Aptos');line(s,76,500,260,C.cyan);tx(s,76,529,1020,30,'The paper’s contribution is not a universal technology winner. It is a transparent map of where pathway portfolios matter for wellbeing—and where the database cannot yet answer.',16,'B7CDD7',false,'Aptos');}

for (const s of p.slides.items) { if (!s.notes) continue; }
const file=await PresentationFile.exportPptx(p);await file.save(OUT);
